# Generated by Django 4.1.3 on 2022-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=350, verbose_name="Announcement title"),
                ),
                (
                    "english_markdown",
                    models.TextField(verbose_name="Announcement english markdown"),
                ),
                (
                    "arabic_markdown",
                    models.TextField(verbose_name="Announcement arabic markdown"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Activate announcement"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
    ]
