# Generated by Django 4.1.3 on 2022-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Offer item value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350, verbose_name="Offer title")),
                (
                    "offer_percentage",
                    models.IntegerField(verbose_name="Offer percentage"),
                ),
                (
                    "plan_duration_offer",
                    models.BooleanField(
                        default=False, verbose_name="Activate offer on plan duration"
                    ),
                ),
                (
                    "plan_type_offer",
                    models.BooleanField(
                        default=False, verbose_name="Activate offer for plan type"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "offer_for",
                    models.ManyToManyField(
                        to="offers.offeritem", verbose_name="Offer for"
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
    ]
