# Generated by Django 4.1.3 on 2022-11-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_offeritem_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeritem",
            name="is_duration",
            field=models.BooleanField(
                default=False, verbose_name="Offer item is plan duration"
            ),
        ),
    ]
