# Generated by Django 4.1.3 on 2022-11-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_offeritem_is_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offeritem",
            name="is_duration",
        ),
    ]
