# Generated by Django 4.1.3 on 2023-01-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=350, verbose_name="Category")),
                (
                    "en_name",
                    models.CharField(max_length=350, verbose_name="Meal english name"),
                ),
                (
                    "ar_name",
                    models.CharField(max_length=350, verbose_name="Meal arabic name"),
                ),
                ("serving", models.IntegerField(verbose_name="Serving")),
                ("protein", models.FloatField(verbose_name="Protein")),
                ("fats", models.FloatField(verbose_name="Fats")),
                ("carbs", models.FloatField(verbose_name="Carbs")),
                ("total_kcal", models.FloatField(verbose_name="Total kcal")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Food item",
                "verbose_name_plural": "Food items",
            },
        ),
        migrations.CreateModel(
            name="MealPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Meal preset name"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("selected_food_items", models.ManyToManyField(to="meals.fooditem")),
            ],
            options={
                "verbose_name": "Meal preset",
                "verbose_name_plural": "Meal presets",
            },
        ),
    ]
