# Generated by Django 4.1.3 on 2023-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_meal_contain_protein_supplement"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="is_refeed_snack",
            field=models.BooleanField(default=False),
        ),
    ]
