# Generated by Django 4.1.3 on 2023-02-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_meal_is_refeed_snack"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Meal type name"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Meal type",
                "verbose_name_plural": "Meals types",
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meals.mealtype",
                verbose_name="Meal type",
            ),
        ),
    ]
