# Generated by Django 4.1.3 on 2023-02-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_meal_recommendation_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="recommendation_index",
            new_name="recommendation_indexes",
        ),
    ]
