# Generated by Django 4.1.3 on 2023-04-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0013_remove_meal_category_mealitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="preparation_description",
            field=models.TextField(
                default="Meal item preparation description",
                verbose_name="Meal item preparation description",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="video_link",
            field=models.CharField(
                default="Video Link Here", max_length=350, verbose_name="Video link"
            ),
        ),
    ]
