# Generated by Django 4.1.3 on 2023-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_account_type_remove_user_phone_num_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Allowed View Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, verbose_name="Allowed view slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        null=True, verbose_name="Allowed View Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Allowed View",
                "verbose_name_plural": "Allowed Views",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="allowed_views",
        ),
        migrations.AddField(
            model_name="user",
            name="allowed_views",
            field=models.ManyToManyField(
                to="accounts.allowedview", verbose_name="Allowed Views"
            ),
        ),
    ]
