# Generated by Django 4.1.3 on 2023-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_allowedview_remove_user_allowed_views_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.CharField(
                default="Full name", max_length=350, verbose_name="Full name"
            ),
            preserve_default=False,
        ),
    ]
