# Generated by Django 4.1.3 on 2023-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_logged_in",
            field=models.BooleanField(
                default=False, verbose_name="This user is logged in"
            ),
        ),
    ]
