# Generated by Django 4.1.3 on 2023-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_logged_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="allowed_views",
            field=models.ManyToManyField(
                null=True, to="accounts.allowedview", verbose_name="Allowed Views"
            ),
        ),
    ]
