# Generated by Django 4.1.3 on 2023-03-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=350, verbose_name="Action")),
                (
                    "user_device",
                    models.CharField(max_length=350, verbose_name="User Device"),
                ),
                (
                    "geolocation",
                    models.CharField(max_length=350, verbose_name="Geo Location"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
            ],
            options={
                "verbose_name": "Website log",
                "verbose_name_plural": "Website logs",
            },
        ),
    ]
