# Generated by Django 4.1.3 on 2023-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitelog",
            name="platform",
            field=models.CharField(default="", max_length=350, verbose_name="Platform"),
            preserve_default=False,
        ),
    ]
