# Generated by Django 4.1.3 on 2022-11-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalTrainingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=100, verbose_name="Phone Number"),
                ),
                (
                    "cor",
                    models.CharField(
                        max_length=100, verbose_name="Country of residence"
                    ),
                ),
                (
                    "payment_currency",
                    models.CharField(max_length=100, verbose_name="Payment currency"),
                ),
                ("age", models.IntegerField(verbose_name="Age")),
                ("gender", models.CharField(max_length=100, verbose_name="Gender")),
                ("weight", models.IntegerField(verbose_name="Weight")),
                ("height", models.FloatField(verbose_name="Height")),
                (
                    "plan_program",
                    models.CharField(max_length=100, verbose_name="Plan program"),
                ),
                (
                    "plan_duration",
                    models.CharField(max_length=100, verbose_name="Plan duration"),
                ),
                (
                    "followup_package",
                    models.CharField(max_length=100, verbose_name="Follow-up package"),
                ),
            ],
            options={
                "verbose_name": "Personal training request",
                "verbose_name_plural": "Personal training requests",
            },
        ),
    ]
