# Generated by Django 4.1.3 on 2022-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="computed_total_price",
            field=models.FloatField(default=0.0, verbose_name="Computed total price"),
            preserve_default=False,
        ),
    ]
