# Generated by Django 4.1.3 on 2023-03-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="assigned_to",
            field=models.CharField(
                max_length=350, null=True, verbose_name="Assigned To"
            ),
        ),
    ]
