# Generated by Django 4.1.3 on 2022-11-05 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0002_personaltrainingrequest_computed_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Timestamp",
            ),
            preserve_default=False,
        ),
    ]
