# Generated by Django 4.1.3 on 2022-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0003_personaltrainingrequest_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="proceeded",
            field=models.BooleanField(
                default=False, verbose_name="Request is proceeded"
            ),
        ),
    ]
