# Generated by Django 4.1.3 on 2023-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0004_personaltrainingrequest_proceeded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaltrainingrequest",
            name="timestamp",
            field=models.DateTimeField(verbose_name="Timestamp"),
        ),
    ]
