# Generated by Django 4.1.3 on 2022-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0004_personaltrainingrequest_proceeded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaltrainingrequest",
            name="payment_currency",
        ),
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="paying_region",
            field=models.CharField(
                default="not yet specified",
                max_length=100,
                verbose_name="Paying region",
            ),
            preserve_default=False,
        ),
    ]
