# Generated by Django 4.1.3 on 2022-11-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_training",
            "0005_remove_personaltrainingrequest_payment_currency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="computed_price_after_sale",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Computed price after sale"
            ),
        ),
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="has_sale",
            field=models.BooleanField(default=False, verbose_name="Sale is activated"),
        ),
    ]
