# Generated by Django 4.1.3 on 2023-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0006_alter_personaltrainingrequest_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaltrainingrequest",
            name="proceeded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Proceeded at"
            ),
        ),
    ]
