# Generated by Django 4.1.3 on 2023-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_plan_algorithm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplanmeal",
            name="meal_category",
            field=models.CharField(
                default="Meal category", max_length=350, verbose_name="Meal Category"
            ),
            preserve_default=False,
        ),
    ]
