# Generated by Django 4.1.3 on 2023-05-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_plan_algorithm", "0002_nutritionplanmeal_meal_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplanmealitem",
            name="carbs",
            field=models.FloatField(
                default=1.11, verbose_name="Carbohydrates per serving"
            ),
        ),
        migrations.AddField(
            model_name="nutritionplanmealitem",
            name="fats",
            field=models.FloatField(default=1.11, verbose_name="Fats per serving"),
        ),
        migrations.AddField(
            model_name="nutritionplanmealitem",
            name="protein",
            field=models.FloatField(default=1.11, verbose_name="Protein per serving"),
        ),
        migrations.AddField(
            model_name="nutritionplanmealitem",
            name="serving",
            field=models.IntegerField(default=1, verbose_name="Serving"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nutritionplanmealitem",
            name="total_kcal",
            field=models.FloatField(default=1.11, verbose_name="Total kcal"),
        ),
    ]
