# Generated by Django 4.1.3 on 2023-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="follow_up_package",
            field=models.CharField(
                default="follow uo package",
                max_length=350,
                verbose_name="Follow up package",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                default="phone number", max_length=350, verbose_name="Phone number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="plan_duration",
            field=models.IntegerField(default=1, verbose_name="Plan duration"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="plan_type",
            field=models.CharField(
                default="plan type", max_length=350, verbose_name="Plan Type"
            ),
            preserve_default=False,
        ),
    ]
