# Generated by Django 4.1.3 on 2023-05-11 23:25

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_plan_algorithm", "0003_nutritionplanmealitem_carbs_and_more"),
        ("clients", "0002_client_follow_up_package_client_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterInTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_take",
                    models.CharField(max_length=150, verbose_name="Water in-take"),
                ),
                ("unit", models.CharField(max_length=350, verbose_name="Unit")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Related client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Water in-take tracking",
                "verbose_name_plural": "Water in-take trackings",
            },
        ),
        migrations.CreateModel(
            name="MealIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Meal uploaded",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Time stamp"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nutrition_plan_algorithm.nutritionplanmeal",
                        verbose_name="Related meal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal in-take tracking",
                "verbose_name_plural": "Meal in-take trackings",
            },
        ),
    ]
