# Generated by Django 4.1.3 on 2023-05-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_waterintake_mealintake"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdata",
            name="water_in_take",
            field=models.IntegerField(default=1, verbose_name="Daily water in take"),
            preserve_default=False,
        ),
    ]
