# Generated by Django 4.1.3 on 2023-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_alter_clientdata_excluded_food_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waterintake",
            name="unit",
        ),
        migrations.AlterField(
            model_name="waterintake",
            name="in_take",
            field=models.FloatField(max_length=150, verbose_name="Water in-take"),
        ),
    ]
