# Generated by Django 4.1.3 on 2023-05-19 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0007_remove_waterintake_unit_alter_waterintake_in_take"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(max_length=350, verbose_name="Follow up note"),
                ),
                (
                    "status",
                    models.CharField(max_length=350, verbose_name="Follow-up status"),
                ),
                (
                    "scheduled_time",
                    models.TimeField(verbose_name="Scheduled follow-up time"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_client",
                        to="clients.client",
                        verbose_name="Related client",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_coach",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Related coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client follow-up",
                "verbose_name_plural": "Cliens follow-ups",
            },
        ),
    ]
