# Generated by Django 4.1.3 on 2023-05-17 11:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_allowed_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Profile pic"
            ),
        ),
    ]
