# Generated by Django 4.1.3 on 2023-05-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_name",
                    models.CharField(max_length=350, verbose_name="Conversatoin name"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "user_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_user_1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User 1",
                    ),
                ),
                (
                    "user_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_user_2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support conversation",
                "verbose_name_plural": "Support conversatoins",
            },
        ),
        migrations.CreateModel(
            name="SupportConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support.supportconversation",
                        verbose_name="Related conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Message's sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support conversation message",
                "verbose_name_plural": "Support conversation messages",
            },
        ),
    ]
