# Generated by Django 4.1.3 on 2023-05-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0003_alter_supportconversationmessage_sender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportconversationmessage",
            name="seen_by",
        ),
        migrations.AlterField(
            model_name="supportconversationmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Message's sender",
            ),
        ),
        migrations.DeleteModel(
            name="UserSeenMessage",
        ),
    ]
