# Generated by Django 4.1.3 on 2023-05-19 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0004_remove_supportconversationmessage_seen_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportInquiryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Inquiry message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_staff_member",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Replied by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support inquiry message",
                "verbose_name_plural": "Support inquiry messages",
            },
        ),
        migrations.CreateModel(
            name="SupportInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Related client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support inquiry",
                "verbose_name_plural": "Support inquires",
            },
        ),
    ]
