# Generated by Django 4.1.3 on 2023-05-19 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0005_supportinquirymessage_supportinquiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportinquirymessage",
            name="replied_by",
        ),
        migrations.AddField(
            model_name="supportinquirymessage",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_account",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sent by",
            ),
        ),
    ]
