# Generated by Django 4.1.3 on 2023-05-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_remove_supportinquirymessage_replied_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportinquirymessage",
            name="inquiry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_support_inquiry",
                to="support.supportinquiry",
                verbose_name="Related support inquiry",
            ),
        ),
    ]
