# Generated by Django 4.1.3 on 2023-06-15 17:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=350, verbose_name="Muscle name")),
                (
                    "img",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Muscle image",
                    ),
                ),
                ("img_link", models.URLField(verbose_name="Muscle image link")),
            ],
            options={
                "verbose_name": "Muscle",
                "verbose_name_plural": "Muscles",
            },
        ),
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Muscle group name"),
                ),
            ],
            options={
                "verbose_name": "Muscle group",
                "verbose_name_plural": "Muscle groups",
            },
        ),
        migrations.CreateModel(
            name="WorkoutLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Workout level"),
                ),
            ],
            options={
                "verbose_name": "Workout level",
                "verbose_name_plural": "Workout levels",
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=350, verbose_name="Workout name")),
                (
                    "video",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Workout video",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Workout video"
                    ),
                ),
                (
                    "complexity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout_plan_algorithm.workoutlevel",
                        verbose_name="Workout complexity",
                    ),
                ),
                (
                    "related_muscle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout_plan_algorithm.muscle",
                        verbose_name="Related muscle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
            },
        ),
        migrations.AddField(
            model_name="muscle",
            name="related_muscle_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workout_plan_algorithm.musclegroup",
                verbose_name="Related muscle group",
            ),
        ),
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=350, verbose_name="Injury name")),
                ("level", models.CharField(max_length=350, verbose_name="Level")),
                (
                    "explaination_video",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Injury Explaination video",
                    ),
                ),
                (
                    "explaination_video_link",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Injury Explaination video",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Injury explaination video"),
                ),
                (
                    "excluded_workouts",
                    models.ManyToManyField(
                        to="workout_plan_algorithm.workout",
                        verbose_name="Excluded workouts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Injury",
                "verbose_name_plural": "Injuries",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Equipment name"),
                ),
                (
                    "img",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Equipment image",
                    ),
                ),
                (
                    "img_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Equipment image link"
                    ),
                ),
                (
                    "related_muscle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout_plan_algorithm.muscle",
                        verbose_name="Related muscle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipments",
            },
        ),
    ]
