# Generated by Django 4.1.3 on 2023-06-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout_plan_algorithm", "0003_workout_related_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="related_accesor_muscle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_muscle",
                to="workout_plan_algorithm.muscle",
                verbose_name="Accesor muscle",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="related_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_muscle_accesor",
                to="workout_plan_algorithm.equipment",
                verbose_name="Related equipment",
            ),
        ),
    ]
