# Generated by Django 4.1.3 on 2023-06-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workout_plan_algorithm",
            "0005_remove_workout_related_accesor_muscle_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_home_workout",
            field=models.BooleanField(default=False, verbose_name="Is home workout ?"),
        ),
    ]
