# Generated by Django 4.1.3 on 2023-06-15 18:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout_plan_algorithm", "0006_workout_is_home_workout"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="workout_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Workout thumbnail"
            ),
        ),
    ]
