# Generated by Django 4.1.3 on 2023-06-15 18:38

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout_plan_algorithm", "0007_workout_workout_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Excercise name"),
                ),
                (
                    "workout_thumbnail",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Excercise thumbnail",
                    ),
                ),
                (
                    "video",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Excercise video",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Excercise video"
                    ),
                ),
                (
                    "is_home_workout",
                    models.BooleanField(
                        default=False, verbose_name="Is home excercise ?"
                    ),
                ),
                (
                    "related_accessory_muscle",
                    models.ManyToManyField(
                        related_name="related_accessory_muscle_muscle",
                        to="workout_plan_algorithm.muscle",
                        verbose_name="Accessory muscle",
                    ),
                ),
                (
                    "related_equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_equipment",
                        to="workout_plan_algorithm.equipment",
                        verbose_name="Related equipment",
                    ),
                ),
                (
                    "related_muscle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout_plan_algorithm.muscle",
                        verbose_name="Related muscle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excercise",
                "verbose_name_plural": "Excercises",
            },
        ),
        migrations.DeleteModel(
            name="Workout",
        ),
        migrations.AlterField(
            model_name="injury",
            name="excluded_workouts",
            field=models.ManyToManyField(
                to="workout_plan_algorithm.excercise",
                verbose_name="Excluded excercises",
            ),
        ),
    ]
