# Generated by Django 4.1.3 on 2023-07-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout_plan_algorithm", "0008_excercise_delete_workout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="related_muscle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workout_plan_algorithm.muscle",
                verbose_name="Related muscle",
            ),
        ),
        migrations.RemoveField(
            model_name="excercise",
            name="related_equipment",
        ),
        migrations.AddField(
            model_name="excercise",
            name="related_equipment",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="workout_plan_algorithm.equipment",
                verbose_name="Related equipment",
            ),
        ),
    ]
