# Generated by Django 4.1.3 on 2023-07-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout_plan_algorithm", "0009_alter_equipment_related_muscle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="excercise",
            name="related_muscle",
        ),
        migrations.AddField(
            model_name="excercise",
            name="related_muscle",
            field=models.ManyToManyField(
                to="workout_plan_algorithm.muscle", verbose_name="Related muscle"
            ),
        ),
    ]
