# Generated by Django 4.1.3 on 2023-07-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout_plan_algorithm", "0010_remove_excercise_related_muscle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="excercise",
            name="stabilizers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="stabilizers_muscle",
                to="workout_plan_algorithm.muscle",
            ),
        ),
    ]
