# Generated by Django 4.1.3 on 2023-01-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(max_length=10, verbose_name="Subscription ID"),
                ),
                (
                    "fullname",
                    models.CharField(max_length=350, verbose_name="User full name"),
                ),
                ("weight", models.IntegerField(verbose_name="Weight")),
                ("height", models.IntegerField(verbose_name="Height")),
                ("age", models.IntegerField(verbose_name="Age")),
                ("body_fat", models.IntegerField(verbose_name="Body fat percentage")),
                (
                    "body_fat_calc_method",
                    models.CharField(
                        max_length=350, verbose_name="Body fat calculation method"
                    ),
                ),
                (
                    "training_volume",
                    models.CharField(max_length=150, verbose_name="Training volume"),
                ),
                (
                    "activity_per_day",
                    models.CharField(max_length=100, verbose_name="Activity per day"),
                ),
                ("goal", models.CharField(max_length=100, verbose_name="User goal")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "excluded_food_items",
                    models.ManyToManyField(
                        related_name="excluded_food_items",
                        to="meals.fooditem",
                        verbose_name="User excluded food items",
                    ),
                ),
                (
                    "prefered_food_items",
                    models.ManyToManyField(
                        related_name="prefered_food_items",
                        to="meals.fooditem",
                        verbose_name="Prefered food item",
                    ),
                ),
            ],
            options={
                "verbose_name": "User data",
                "verbose_name_plural": "Users data",
            },
        ),
        migrations.CreateModel(
            name="ClientMacros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lean_body_mass", models.IntegerField(verbose_name="Lean body mass")),
                ("bmr", models.IntegerField(verbose_name="BMR")),
                ("total_calories", models.IntegerField(verbose_name="Total calories")),
                (
                    "calories_deficit",
                    models.IntegerField(verbose_name="Calories deficit"),
                ),
                ("protein_grams", models.IntegerField(verbose_name="Protein grams")),
                ("fat_grams", models.IntegerField(verbose_name="Fat grams")),
                ("carb_grams", models.IntegerField(verbose_name="Carb grams")),
                (
                    "computed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Computed at"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs_generator.clientdata",
                        verbose_name="Related user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User calories calculation",
                "verbose_name_plural": "Users calories calculations",
            },
        ),
    ]
