# Generated by Django 4.1.3 on 2023-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs_generator", "0002_clientdata_can_take_protein_supplement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdata",
            name="can_take_protein_supplement",
            field=models.BooleanField(
                default=False, verbose_name="Can take protein supplement"
            ),
        ),
    ]
