# Generated by Django 4.1.3 on 2023-01-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs_generator", "0003_alter_clientdata_can_take_protein_supplement"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdata",
            name="prefered_number_of_meals",
            field=models.IntegerField(
                default=3, verbose_name="Prefered number of meals"
            ),
            preserve_default=False,
        ),
    ]
