# Generated by Django 4.1.3 on 2023-01-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=350, verbose_name="Announcement title"),
                ),
                (
                    "english_markdown",
                    models.TextField(verbose_name="Announcement english markdown"),
                ),
                (
                    "arabic_markdown",
                    models.TextField(verbose_name="Announcement arabic markdown"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Activate announcement"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.CreateModel(
            name="OfferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=350, verbose_name="Offer item value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350, verbose_name="Offer title")),
                (
                    "offer_percentage",
                    models.IntegerField(verbose_name="Offer percentage"),
                ),
                (
                    "plan_duration_offer",
                    models.BooleanField(
                        default=False, verbose_name="Activate offer on plan duration"
                    ),
                ),
                (
                    "plan_type_offer",
                    models.BooleanField(
                        default=False, verbose_name="Activate offer for plan type"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "offer_for",
                    models.ManyToManyField(
                        to="offers.offeritem", verbose_name="Offer for"
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
    ]
