# Generated by Django 4.1.3 on 2023-01-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_meal_mealitem_delete_mealpreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="contain_protein_supplement",
            field=models.BooleanField(
                default=False, verbose_name="This meal contains protein supplement"
            ),
        ),
    ]
