# Generated by Django 4.1.3 on 2023-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0005_mealtype_meal_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="recommendation_months",
            field=models.CharField(
                max_length=30, null=True, verbose_name="This meal recommended for"
            ),
        ),
    ]
