# Generated by Django 4.1.3 on 2023-02-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_meal_recommendation_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="recommendation_index",
            field=models.CharField(
                max_length=350, null=True, verbose_name="Recommendation index"
            ),
        ),
    ]
