# Generated by Django 4.1.3 on 2023-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0008_rename_recommendation_index_meal_recommendation_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="calc_per_piece",
            field=models.BooleanField(
                default=False,
                verbose_name="This food item should be calculated per piece ?",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="per_piece_serving",
            field=models.FloatField(default=0.0, verbose_name="Per piece serving"),
        ),
    ]
