# Generated by Django 4.1.3 on 2023-03-10 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personal_training", "0002_personaltrainingrequest_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaltrainingrequest",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
    ]
