# Generated by Django 4.1.3 on 2023-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_training", "0003_alter_personaltrainingrequest_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltrainingrequest",
            name="proceeded_at",
            field=models.DateTimeField(null=True, verbose_name="Proceeded at"),
        ),
    ]
