# Generated by Django 4.1.3 on 2022-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquires", "0002_inquiry_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="proceeded",
            field=models.BooleanField(default=False, verbose_name="Request proceeded"),
        ),
    ]
