# Generated by Django 4.1.3 on 2023-03-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinetrainingtaskmember",
            name="number_of_assigned_tasks",
            field=models.IntegerField(
                default=0, verbose_name="Number of assigned tasks"
            ),
        ),
    ]
